### ISSUE TITLE
[Suggestion] Pull list of domains from file

### ISSUE THREAD

**Issue by uBadRequest** [felixfriedrich/dnsmonitor#1]
Hello @felixfriedrich !

Thanks for sharing your code man! Looks nice! :+1: 

It would be really awesome if you could add the ability to grab domains from a file. I have too many domains I want to monitor.

**Comment by felixfriedrich** [comment]
Thanks! I certainly have the plan to add the possibility to use a config file as well. If you want to create a pull request for this, I am happy to accept it.

**Comment by felixfriedrich** [comment]
@uBadRequest I've just release version 0.4, which is now able to read domains from a yml file. Feedback is very welcome :-)

**Comment by felixfriedrich** [comment]
@uBadRequest Did you have a change to use one of the latest releases? More feedback is very welcome.
